### ISSUE TITLE
[Linux] Can't use Kaku

### ISSUE THREAD

**Issue by PrzemekSkw** [EragonJ/Kaku#489] opened 2017-03-05 21:35 UTC
Hello, sometimes age Kaku work very good. Now after few updates I can't play any song. When I click on some track I see only reloading circle and nothing happens.

What is your Kaku version?

1.8.5 

What is your OS (with version number)?

Fedora 25 Gnome
Linux 4.9.12-200.fc25.x86_64 #1 SMP Thu Feb 23 19:31:49 UTC 2017 x86_64

Which platform are you using to listen to music?

YouTube 

Which track format are you using?

best video

Regards,

**Comment by EragonJ** [comment] 2017-03-06 06:26
@PrzemekSkw can you write down more details ? If you have screenshots, that would be better. You can also open developer tool and jump to console tab and see whether there is any error message showing up, anything will be helpful.

BTW, did you try to use `update Player` in settings page ? Sometimes that can solve problems.

**Comment by PrzemekSkw** [comment] 2017-03-06 08:07
Hi, that's console output:
![zrzut ekranu z 2017-03-06 08-55-48](https://cloud.githubusercontent.com/assets/25219988/23601467/e4d737b2-024b-11e7-986d-2430bc66e347.png)

when I make update player I also have error:
![zrzut ekranu z 2017-03-06 09-06-22](https://cloud.githubusercontent.com/assets/25219988/23601533/4a39e992-024c-11e7-9437-fbbb62cfe804.png)

**Comment by Mladenovic92** [comment] 2017-03-15 01:25
i'm getting same error as @PrzemekSkw

**Comment by funilrys** [comment] 2017-03-15 05:37
can you give us 
`ls -al /tmp/.mount_8cwbWe/usr/bin/ressources/app.asar.unpacked/node_modules
`ls -al /tmp/.mount_8cwbWe/usr/bin/ressources/app.asar.unpacked/node_modules/youtube-dl/bin/`

**Comment by funilrys** [comment] 2017-03-15 07:04
@EragonJ Do you have a copy of the AppImage before compilation? I'd like to take a look at it :wink: 
  
Just installed Kaku into a fresh Linux Mint (VM) and it seem that `/tmp/.mount_*` Don't have any owner/group which is _illegal_ and my cause some weird bugs...

In between, As root we can't change/fix permissions so the only way is to take a look at the source code and try to recompile ...

**Comment by funilrys** [comment] 2017-03-15 07:06
Result of ls -al for /tmp/ @EragonJ 
![deepinscreenshot20170315080548](https://cloud.githubusercontent.com/assets/14127285/23937137/3ceb83a2-0956-11e7-9398-8d40ce68aa7c.png)

**Comment by PrzemekSkw** [comment] 2017-03-15 11:35
The output is: No such file or directory

**Comment by funilrys** [comment] 2017-03-15 13:07
@PrzemekSkw It's normal you have to execute kaku in same time :smile:

**Comment by Mladenovic92** [comment] 2017-03-15 13:14
@funilrys 
![_092](https://cloud.githubusercontent.com/assets/6660598/23949975/b05fcb62-0989-11e7-8e0c-8e5fab6c23f9.png)

**Comment by funilrys** [comment] 2017-03-15 13:51
@Mladenovic92 @PrzemekSkw Aww forgot that AppImage generate a random string after .mount_ so yoou have to find the current .mount_*/usr/bin/ressources/app.asar.unpacked/node_modules

**Comment by PrzemekSkw** [comment] 2017-03-15 15:57
@funilrys sory don't understand what to do

**Comment by funilrys** [comment] 2017-03-15 16:56
Thanks @Mladenovic92 but it's strange gonna investigate myself :)

**Comment by Mladenovic92** [comment] 2017-03-15 17:03
@funilrys 
![_095](https://cloud.githubusercontent.com/assets/6660598/23960919/9e395708-09a9-11e7-907a-393cd6054946.png)

**Comment by funilrys** [comment] 2017-03-15 17:11
Is it working @Mladenovic92 ? Cause actually if you have those permissions normally you don't have the bug referred by OP

**Comment by Mladenovic92** [comment] 2017-03-15 17:18
Nope, it is just loading and never starts.
here look: http://webmshare.com/8yR8r

**Comment by funilrys** [comment] 2017-03-15 17:18
Okay @EragonJ We have a real problem around there :sweat_smile:  ... It's all about appimage

**Comment by funilrys** [comment] 2017-03-15 17:22
We have to fins a solution asap, cause this may be reported to ALL linux distributions ... @EragonJ 
``` bash
$ /tmp/.mount_AhXeDX/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl -vU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.6.0 - Linux-4.10.1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
Updating to version 2017.03.15 ...
ERROR: no write permissions on /tmp/.mount_AhXeDX/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl
```

**Comment by LittleWhite-tb** [comment] 2017-03-15 18:57
If it can helps.
With `ls` as normal user : 
`
  1 dr-xr-xr-x  1 root      root    2048  5 déc.  16:05 .mount_3erBsr
`
Same ls as root :
`
d?????????  ? ?         ?          ?              ? .mount_3erBsr
`

**Comment by funilrys** [comment] 2017-03-15 18:58
thanks @LittleWhite-tb gonna work on a fix/workaround tomorrow (Berlin Time)

**Comment by EragonJ** [comment] 2017-03-16 07:13
@funilrys thanks for the help, since i don't have linux, it's hard for me to investigate this issue. If you can help on this part, it would be a big help !

**Comment by LittleWhite-tb** [comment] 2017-03-16 21:07
Not a problem of rights, or something like this (sorry if I mislead you yesterday).
Here what happens when running the youtube-dl command out of Kaku (I just added verbose flag) : 
```
/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl --verbose --dump-json -f best --no-check-certificate --no-cache-dir -f best http://www.youtube.com/watch?v=FM7MFYoylVs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--dump-json', '-f', 'best', '--no-check-certificate', '--no-cache-dir', '-f', 'best', 'http://www.youtube.com/watch?v=FM7MFYoylVs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.6.0 - Linux-4.4.52-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'
Traceback (most recent call last):
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl67GkkS/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I have youtube-dl installed locally (I mean separately of Kaku). The Kaku's version is outdated :
```
/tmp/.mount_5Ue0Ph/usr/bin/resources/app.asar.unpacked/node_modules/youtube-dl/bin/youtube-dl --version
2016.12.01
youtube-dl --version
2017.03.07
```

When using the locally installed youtube-dl, the command results normally.
Thus, if you release 1.9.0 soon, I suppose you have to embedded youtube-dl and voilà, Linux's users will be happy.

The read-only file system is related to the auto-update feature. Effectively, it seems that AppImage goes to some special (hence the ? from ls) kind of folder, which is in read only mode (you can see it as point 7 of AppImageKit https://github.com/probonopd/AppImageKit/blob/master/README.md ).

Finally,  I can see two solutions :
- Try to use the applications already installed on user machine (because, I have the good youtube-dl version locally, even before using Kaku)
- You can try auto updating AppImage -> https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md (but, this will work only for new version of Kaku, not for internals of Kaky)

**Comment by funilrys** [comment] 2017-03-16 22:41
Already on it @LittleWhite-tb :wink:

**Comment by EragonJ** [comment] 2017-03-17 04:38
> Signature extraction failed

I remember this error message is coming from `youtube-dl` which means youtube-dl needs to be updated.

> Make applications read-only. Since AppImages are read-only by design, the user can be reasonably sure that an app does not modify itself during operation.

Ok this is kinda surprising because sometimes `youtube-dl` needs to be updated so make sure it fits latest youtube encryption rules and that's why there is one `Update Player` button in settings panel to make sure users can click on it to force update `youtube-dl`.

The mindset in AppImage is good but because Kaku is a special program based on `youtube-dl`, may need to figure out a different solution. Or, linux people need to use their own platform-specific binaries to make this feature work.

**Comment by funilrys** [comment] 2017-04-05 10:32
Hey @EragonJ I have a solution for Linux but don't know if you're gonna like it :) #Gitter

**Comment by EragonJ** [comment] 2017-04-07 02:29
@funilrys go for it !! any help would be welcome!

**Comment by probonopd** [comment] 2017-04-07 05:38
When you bundle `youtube-dl` and you need to update it, then you need to update the whole AppImage. That is by design. This way you can always check the sha checksum of the file and be sure what you run. I don't like applications that change themselves.

**Comment by EragonJ** [comment] 2017-04-07 10:36
@probonopd that's the main problem because `youtube-dl` is updated often but Kaku itself is not. So instead of releasing Kaku every few days, the better way is to let users update it by themselves. Is there any way we can bypass the read-only limitations in AppImage ? or any other ways ?

**Comment by funilrys** [comment] 2017-04-07 10:42
.deb will be done for this weekend normally :smile: and arch user shouldn't have problem with the patch or the application of the solution I told you @EragonJ

**Comment by probonopd** [comment] 2017-04-07 15:47
@EragonJ of course you could have users install `youtube-dl` into somewhere on the `$PATH` and just use that.

**Comment by funilrys** [comment] 2017-04-07 16:10
Good idea @probonopd 
We could provide `youtube-dl` as a different package @EragonJ ...

**Comment by koxu1996** [comment] 2017-04-08 14:55
Latest Kaku does not play songs on Ubuntu 16.04 too.

**Comment by funilrys** [comment] 2017-04-08 15:27
@koxu1996 I try to do my best to provide a package ;) I may need you to test it when I'm done cause I'm not an "Ubuntu fan" but I like to challenge myself :wink:

**Comment by PrzemekSkw** [comment] 2017-04-08 15:38
Maybe flatpak will be good option:)

**Comment by funilrys** [comment] 2017-04-08 15:41
@PrzemekSkw Arch user gonna have an update soon to fix this issue ;) 
I tested it and no it's not resolving the issue with the auto updater ...

**Comment by probonopd** [comment] 2017-04-08 17:04
> Maybe flatpak will be good option:)

If you don't like "one app = one file" and the simplicity that comes with it, then yes, maybe.

**Comment by koxu1996** [comment] 2017-04-08 18:03
@funilrys Of course, I can provide provide feedback and required info.

**Comment by PrzemekSkw** [comment] 2017-04-08 18:36
@probonopd i like option one app one file but on my fedora tgat don't work

**Comment by probonopd** [comment] 2017-04-08 18:38
> on my fedora tgat don't work

Then we need to fix that ;-)

**Comment by EragonJ** [comment] 2017-04-10 08:34
good point, we can move it out of the dev dependency and to somewhere in `$PATH` (we can define our own) hmmmm sounds like a good idea. With this, we can also reduce Kaku's size a lot for windows users and eliminate some build time errors.

**Comment by funilrys** [comment] 2017-04-10 10:27
Hey @EragonJ @PrzemekSwk,
Arch Package is on its way 🙂 Will be available this afternoon after I solve the problem with the .desktop (berlin time)

**Comment by funilrys** [comment] 2017-04-10 11:32
@PrzemekSkw  @Mladenovic92 @LittleWhite-tb  & Arch Users

Please uninstall your current version of Kaku and install with
```
pacaur -S kaku-bin
```

Ubuntu user please stay in hold :)

**Comment by PrzemekSkw** [comment] 2017-04-10 12:05
@funilrys Hi, what about Fedora ?

**Comment by funilrys** [comment] 2017-04-10 13:01
@PrzemekSkw Just add it to my workflow :)

**Comment by PrzemekSkw** [comment] 2017-04-10 13:32
@funilrys OK, so I will wait for good news :)

**Comment by koxu1996** [comment] 2017-04-10 21:31
I am waiting for update. I hope it will solve this errors:
[](https://i.snag.gy/EMFsW6.jpg)

**Comment by probonopd** [comment] 2017-04-10 21:36
Does it expect a read-write filesystem? AppImage is read-only by design.

**Comment by Mladenovic92** [comment] 2017-04-10 21:37
for me it is working now
Arch Linux

**Comment by funilrys** [comment] 2017-04-11 07:18
@koxu1996 What's your OS ?

**Comment by koxu1996** [comment] 2017-04-11 08:47
@EragonJ Ubuntu 16.04

**Comment by funilrys** [comment] 2017-04-11 09:01
Okay thanks @koxu1996 the great news is that I'm working on the .deb package so it'll be fixed asap :)

**Comment by koxu1996** [comment] 2017-04-21 17:28
@funilrys Any updates?

**Comment by ndstate** [comment] 2017-05-05 17:19
Hello, I am also having issues in Ubuntu 16.04

**Comment by PrzemekSkw** [comment] 2017-05-05 17:54
I'm on Manjaro now and installed Kaku from Aur and also don't work.

**Comment by koxu1996** [comment] 2017-05-05 18:17
Kaku does not work on Linux for a half year so it is not worth installing it.

**Comment by funilrys** [comment] 2017-05-12 20:48
Okay guys I'm back !! First sorry for the waiting time I was under exams.

Just publish a update for archlinux @PrzemekSkw just update (`pacaur -S kaku-bin`) open kaku then use the autoupdater :)

Other: I'm rechrooting debian currently so x64 package will be on his way asap (can't tell when but it's gonna be done)

**Comment by PrzemekSkw** [comment] 2017-05-15 06:50
@funilrys Hi I install from AUR kaku-bin ver. 1.8.5-2 and it works now :D thanks
Regards.

**Comment by EragonJ** [comment] 2017-05-15 07:22
@PrzemekSkw @funilrys ++++ it's awesome lol

**Comment by na-ji** [comment] 2017-05-17 09:42
Waiting to test it @funilrys !

**Comment by funilrys** [comment] 2017-05-17 12:58
@koxu1996 @na-ji Please [test it ](http://ilrysfun.com/kaku_1.8.5-1_amd64.deb)! :)

**Comment by na-ji** [comment] 2017-05-17 13:08
@funilrys : It works perfectly now! Maybe you should also add a shortcut for the binary. :)

**Comment by funilrys** [comment] 2017-05-17 16:32
thanks for feedback @na-ji !

**Comment by koxu1996** [comment] 2017-05-17 16:55
@funilrys It is working now, so next version should be released ASAP

**Comment by funilrys** [comment] 2017-05-17 19:24
@na-ji @koxu1996 Can You remove the previously installed package and install [this one](http://ilrysfun.com/kaku_1.8.5-1_amd64.deb) ? Thanks in advance :+1:

**Comment by koxu1996** [comment] 2017-05-17 20:46
@funilrys What is different in this version?

**Comment by funilrys** [comment] 2017-05-17 20:58
Correction of the internal structure + add links +deletion of some warnings 🙂 I'm under Arch Linux so I just want to know if it's working well for you after the changes 😉

**Comment by koxu1996** [comment] 2017-05-17 21:24
@funilrys It seems to be working fine  :+1:

**Comment by funilrys** [comment] 2017-05-17 21:26
The desktop entry too ? 🙂

**Comment by na-ji** [comment] 2017-05-18 08:21
Yes, thank you there is now a desktop entry. But you forgot to add the logo to the archive. :D

**Comment by funilrys** [comment] 2017-05-18 08:40
Damm!!  thanks @na-ji gonna look at it :joy_cat:

**Comment by funilrys** [comment] 2017-05-18 08:41
@PrzemekSkw do you still have fedora ? I need a tester :)

**Comment by funilrys** [comment] 2017-05-18 09:43
@na-ji [Last test](http://ilrysfun.com/kaku/deb/1.8.5/kaku_1.8.5-2_amd64.deb) and I think we're ready for the next level :+1: thanks a lot :trophy:

**Comment by na-ji** [comment] 2017-05-18 09:58
Everything perfect now @funilrys!
Also I can test on Fedora too if you want. :wink:

**Comment by funilrys** [comment] 2017-05-18 10:10
Awesome just [test it](http://ilrysfun.com/kaku/rpm/kaku-1.8.5-2.x86_64.rpm) @na-ji  :wink:

**Comment by na-ji** [comment] 2017-05-18 10:23
@funilrys The download link does not work

**Comment by funilrys** [comment] 2017-05-18 10:25
@na-ji my bad updated my last answer

**Comment by na-ji** [comment] 2017-05-18 11:14
On fedora 24, I got this error trying to install the .rpm :
`Detailed errors from the package manager follow:

Error running transaction: file / from install of kaku-1.8.5-2.x86_64 conflicts with file from filesystem-3.2-37.fc24.x86_64
file /usr/bin from install of kaku-1.8.5-2.x86_64 conflicts with file from filesystem-3.2-37.fc24.x86_64`

**Comment by funilrys** [comment] 2017-05-18 11:32
Okay thanks 👍

**Comment by EragonJ** [comment] 2017-05-27 13:00
@funilrys can this be closed !?

**Comment by funilrys** [comment] 2017-05-27 13:26
@EragonJ Let's close it but gonna continue commenting for fedora support :+1: The big work is already done :)

**Closed by funilrys** 2017-05-27 13:26 UTC
Labels: bug, in progress, linux
