### ISSUE TITLE
'npm install' fails with errors

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#390] opened 2016-04-14 12:34 UTC
> youtube-dl@1.11.0 postinstall /home/michel/git/Kaku/node_modules/youtube-dl
> node ./scripts/download.js

>module.js:341
    throw err;
    ^

>Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/michel/git/Kaku/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:4:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
>npm ERR! youtube-dl@1.11.0 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.11.0 postinstall script.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

>npm ERR! System Linux 4.4.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /home/michel/git/Kaku
npm ERR! node -v v5.10.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

`npm instal xtend` fixed the issue.

**Comment by EragonJ** [comment] 2016-04-15 03:48
@mimi89999 thanks, i'll check it.

**Comment by EragonJ** [comment] 2016-04-24 01:42
@mimi89999 i can't reproduce that here, can you help to figure out what's the file that causes the problem and which line ? In my youtube-dl, there is no such dependency at all. If you can figure that out, it would be helpful !

**Comment by EragonJ** [comment] 2016-05-11 15:14
This bug is quite related to #396, so closed this one. thanks.

**Closed by EragonJ** 2016-05-11 15:14 UTC
